### ISSUE TITLE
No ledger found

### ISSUE THREAD

**Issue by kimhoegcit** [WietseWind/docker-rippled#13]
Thanks for the docker image, I managed to pull and build a container successfully. However, I noticed that it connected to 10 peers but my ripple node got no ledger. 

I got the following from server_info:
"published_ledger": "none",

May I know how do I got the distributed ledger?

Thanks

**Comment by WietseWind** [comment]
How long did you wait, and are you on fast SSD storage? It can take up to half an hour and requires fast SSD storage to move from connected to peers to actually catching up with the consensus ledger.
