### ISSUE TITLE
Allow only `rippled.cfg` to be supplied

### ISSUE THREAD

**Issue by ckniffen** [WietseWind/docker-rippled#18]
The [entrypoint](https://github.com/WietseWind/docker-rippled/blob/master/entrypoint#L18) requires both `rippled.cfg` and `validators.txt` to be able to specify a custom config.

This will help run the image in standalone mode.  Having `validators.txt` empty throws errors in rippled about it missing stanzas even though its values aren't used when in standalone mode.

**Comment by WietseWind** [comment]
The logic referred to only runs if there's something in the `/config` folder in the container, if you map straight to the rippled config file path it'll work just fine (the entrypoint only executes that logic if there's a rippled config in the `/config` volume mapping in the first place.

Also: it doesn't error if not provided, it just doesn't copy. Meaning you can run with default config or map straight to the `/etc/opt/ripple/rippled.cfg` file in the container.

But: I separated the logic for the two files & pushed a new container image.
