### ISSUE TITLE
why it is so slow to sync Ripple Node ???

### ISSUE THREAD

**Issue by AlbertChanX** [WietseWind/docker-rippled#2]
I take several days to sync the ledgers，there are 20 thousand + ledgers on my node, but there are **40 million** +  ledgers on the main net now. 😭 Is there any way to **speed up** it ? Thx 🤝 
  my critical config  as follows:

`rippled.cfg`

[port_peer]
port = 51235
ip = 0.0.0.0
protocol = peer

[node_size]
small

[node_db]
type=NuDB
path=/var/lib/rippled/db/nudb
advisory_delete=0
online_delete=256

[ledger_history]
256

[ips]
r.ripple.com 51235

`validators.txt`

[validator_list_sites]
https://vl.ripple.com

[validator_list_keys]
ED2677ABFFD1B33AC6FBC3062B71F1E8397C1505E1C42C64D11AD1B28FF73F4734

**Comment by WietseWind** [comment]
Hi!

That takes a long time indeed. If you want to sync full history, prepare to have almost 9 TB of SSD storage ready. If you have, send me a reply. I can add you to my full history server firewall and you can add my node to your peer list, so you can sync it relatively fast (but downloading 9TB will of course take some time).

👋 Wietse

**Comment by salisbury-espinosa** [comment]
@WietseWind 
```
If you have, send me a reply. I can add you to my full history server firewall and you can add my node to your peer list
```
can you add me?

**Comment by salisbury-espinosa** [comment]
@WietseWind Could you share the archive with the data?

**Comment by WietseWind** [comment]
@nbougalis: do you have a recent snapshot?
