### ISSUE TITLE
tx_blob data question

### ISSUE THREAD

**Issue by junghyun0783** [WietseWind/docker-rippled#24]
hello.
I am writing because I have a question.
I have now created a key pair offline and signed the transaction.
A signature was received,
I am trying to create a blob and make a submit RPC call.
Here is the question.
Can the tx_blob value be made into a signature value?
I want to create a tx_blob.
I knew that the signature value was converted to tx_blob (gpt told me).
But maybe I was wrong?

**Comment by junghyun0783** [comment]
hmm....
TxJson {{
   "TransactionType": "Payment",
   "Flags": 2147483648,
   "Sequence": 43892539,
   "DestinationTag": 0,
   "Amount": "999000000",
   "Fee": "10",
   "SigningPubKey": "EDC46BDACDDF3372B87DD73B59C27D177F945F861752D9F43E627864FD59EE70E7",
   "TxnSignature": "C78F62148BB19388731907757A373EE2FC5F0F2D23809B51BF428574255186E21C196518AC7165BBBE9B88916D3372EFBE32063065800A0C591892F0AE2 00103",
   "Account": "rLVrsPSzHabxRXtxTKDNnqVNyCz5f8nzCY",
   "Destination": "r4GdLPf3TxuNGseUJUnuz1czTnLvD8T5Tm"
}}
Isn't this data serialized and converted to hexadecimal value into blob data?

**Comment by WietseWind** [comment]
Serialization and signing usually happens at the stame step with the same function.

Samples using `xrpl-accountlib`:

https://github.com/WietseWind/xrpl-accountlib/blob/master/samples/sign.js

https://github.com/WietseWind/xrpl-accountlib/blob/master/samples/sign-and-submit.mjs

You can then for example use `xrpl-client` to connect & send a `{command: 'submit', tx_blob: '...'}` or use the helper functions as displayed in the sample above.
