### ISSUE TITLE
Dear developer, please help me!

### ISSUE THREAD

**Issue by junghyun0783** [WietseWind/docker-rippled#25]
Dear developer,

Currently, while I was receiving node blocks, my computer crashed, so I rebooted and ran it again, but the blocks did not crash.

I have one question!
Currently, I am running a Ripple node.
But isn't there a site where Ripple can get full node snapshots?
Tron and other coins exist, but does Ripple not exist?

**Comment by WietseWind** [comment]
Can you please define "full node snapshots": do you mean a data dump with the entire Full History database? Are you aware you'd require close to 30TB of SSD storage?

**Comment by junghyun0783** [comment]
@WietseWind 
you're right. This is the entire Full History database.
Um... there are no snapshots for each capacity, right?
I only want to be responsible for signing and sending transactions. A snapshot of reasonable capacity is required.

**Comment by WietseWind** [comment]
A snapshot for just the # of ledgers required to sign and send is 256 ledgers which you can just sync up from peering in minutes. No need for a snapshot, just run your node and it'll sync.

No need for full history to sign and submit tranasctions.

**Comment by WietseWind** [comment]
You easily can, as mentioned you don't need full history to submit transactions.

Just run the docker container and it will sync up, and you'll be good to go for current ledger queries and transaction submission.

**Comment by junghyun0783** [comment]
@WietseWind 
Synchronization has not progressed for over an hour now... If so, is it a hardware problem? It worked fine before the PC was disconnected, but after rebooting, synchronization does not proceed.

**Comment by junghyun0783** [comment]
@WietseWind 
{
    "result": {
        "info": {
            "build_version": "2.0.0",
            "closed_ledger": {
                "age": 2,
                "base_fee_xrp": 1e-05,
                "hash": "B6C02D467927F0CF8A89E01721DA29C80D828346C845FEC323A51ADA0F27BB33",
                "reserve_base_xrp": 10,
                "reserve_inc_xrp": 2,
                "seq": 403
            },
            "complete_ledgers": "empty",
            "hostid": "DOES",
            "io_latency_ms": 1,
            "jq_trans_overflow": "0",
            "last_close": {
                "converge_time_s": 2.005,
                "proposers": 0
            },
            "load_factor": 1,
            "network_id": 1,
            "peer_disconnects": "13",
            "peer_disconnects_resources": "0",
            "peers": 10,
            "ports": [
                {
                    "port": "80",
                    "protocol": [
                        "ws"
                    ]
                },
                {
                    "port": "51235",
                    "protocol": [
                        "peer"
                    ]
                }
            ],
            "pubkey_node": "n9LdfzX241uCY5unBEFzGjxV6DoKxzLqdkX1Vg9PpFBVfx6uPrgS",
            "published_ledger": "none",
            "server_state": "connected",
            "server_state_duration_us": "1345144910",
            "state_accounting": {
                "connected": {
                    "duration_us": "1346146003",
                    "transitions": "2"
                },
                "disconnected": {
                    "duration_us": "129106811",
                    "transitions": "2"
                },
                "full": {
                    "duration_us": "0",
                    "transitions": "0"
                },
                "syncing": {
                    "duration_us": "0",
                    "transitions": "0"
                },
                "tracking": {
                    "duration_us": "0",
                    "transitions": "0"
                }
            },
            "time": "2024-Feb-16 11:21:33.306983 UTC",
            "uptime": 1476,
            "validation_quorum": 5
        },
        "status": "success"
    }
}

**Comment by WietseWind** [comment]
That looks good, you have peers.

Is your docker storage used for this container on your 10TB disk or your 1TB SSD?

It hsould be on your SSD, as the node will not be able to sync up as your IO won't be enough.

**Comment by junghyun0783** [comment]
@WietseWind 
you're right.
  The location set to RAID 0 (10TB disk + 1TB SSD) was designated as storage.
But what was strange was that the synchronization worked well before booting.
Why doesn't it work now? Will I have to wait a bit to find out?

**Comment by junghyun0783** [comment]
@WietseWind 
Ah, could it be a disk I/O problem?
Currently, the tron testnet is also running on this PC.

**Comment by WietseWind** [comment]
99/100 times if it doesn't sync it's an IO limitation, rippled requires a lot of IO to be able to sync up.

**Comment by junghyun0783** [comment]
@WietseWind 
Ah, that's a really logical explanation.
Before that, if I had run the Ripple node first and then the Tron node, Ripple would have used the SSD...
I'll have to stop the Tron node and run it.
thank you!!
Thank you so much.
