### ISSUE TITLE
The TX that was viewed just a moment ago cannot be viewed.

### ISSUE THREAD

**Issue by junghyun0783** [WietseWind/docker-rippled#26]
hello!
I am posting a question because I have a question while operating the node.
We are currently operating a testnet through Docker.
We created a TX through our node and called submit RPC.
TX information was confirmed through the TX PRC function.
however!!
Shockingly, we searched with our TX hash on the "https://blockexplorer" site, but it did not work.... ㅡ0ㅡ
And after some time, we called the TX RPC function with our node... and the TX that was queried was
```
{
     "result": {
         "error": "txnNotFound",
         "error_code": 29,
         "error_message": "Transaction not found.",
         "request": {
             "binary": false,
             "command": "tx",
             "transaction": "A9EAE77170075FAD7491B6795FD6BF7DFCFEB13F952B2694D5FDA14A7FAB1AB0"
         },
         "status": "error"
     }
}
```
It said that it couldn't be found as above...
Why is TX, which was clearly viewable, suddenly not viewable?
What is the reason?
Developer Ko Soo, please. I am very curious about the reason.
Thank you for reading this long article.

**Comment by WietseWind** [comment]
This can mean many things.

Either your node was out on a fork, and it never got validated on the actual network, or you submitted to testnet and looked for the transaction on another network, or it was too long ago (please note that testnet is often not full history).

This is unrelated to this docker container. For more information, please see the xrpl.org docs.
