### ISSUE TITLE
Why is the capacity of containers increasing?

### ISSUE THREAD

**Issue by junghyun0783** [WietseWind/docker-rippled#27]
I am operating a Ripple node through Docker.

Create a container as shown below.
_"docker run -itd --name xrp_testnet -p 40041:5005 -p 40042:51235 -p 40043:80 -p 40044:51234 -p 40045:6006 -p 40046:50051 -p 40047:443 -v /home/docker /container/testnet/xrp/xrp_testnet/config:/etc/opt/ripple/ -v /home/docker/container/testnet/xrp/xrp_testnet/db:/var/lib/rippled/db -v /home/docker/ container/testnet/xrp/xrp_testnet/log:/var/log/rippled xrpllabsofficial/xrpld:latest"_

There is a problem.
Even though I mounted it and removed Ripple's logs and block data, the container's capacity continues to increase.

Why is the capacity of containers increasing?

[root@localhost ~]# df -h
Filesystem Size Used Avail Use% Mounted on
devtmpfs 63G 0 63G 0% /dev
tmpfs 63G 0 63G 0% /dev/shm
tmpfs 63G 18M 63G 1% /run
tmpfs 63G 0 63G 0% /sys/fs/cgroup
**/dev/mapper/centos-root 50G 49G 1.6G 97% /**
/dev/sda2 1014M 332M 683M 33% /boot
/dev/sda1 200M 12M 189M 6% /boot/efi
/dev/mapper/centos-home 12T 4.9T 6.5T 43% /home
tmpfs 13G 0 13G 0% /run/user/0
overlay 50G 49G 1.6G 97% /var/lib/docker/overlay2/786417a4 b8e162ad0c00353c835eb62d894d8249fe03181389bfab904f83723d/merged
overlay 50G 49G 1.6G 97% /var/lib/docker/overlay2/239c0652 f33579598b9b246e1400cb85b0fd0256494b277c7dbdbd352a61b1b5/merged
overlay 50G 49G 1.6G 97% /var/lib/docker/overlay2/36db05b6 7f7ae64fdf06fa6192b7864a756a4748b12406c32d0ac6bacf20fab6/merged

As you can see here, the /dev/mapper/centos-root capacity continues to increase and the container seems to stop.
I'm curious about the cause.

Thank you for reading this long content!!

**Comment by junghyun0783** [comment]
For reference, if you delete the Ripple container,
/dev/mapper/centos-root 50G 8.1G 42G 17% /
As shown above, we were able to confirm that the capacity was reduced.

**Comment by WietseWind** [comment]
That's because the rippled process also reports logs to stdout, so you should also clean the docker container stdout logs ;)
